# Generated by Django 2.2.15 on 2020-08-21 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccination',
            name='drug',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='vaccination', to='application.Drug'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='drug',
            name='description',
            field=models.TextField(max_length=255),
        ),
    ]
